### ISSUE TITLE
Remover lorem ipsum

### ISSUE THREAD

**Issue by huogerac** [Gabriels999/D2.3-Personal-Page#1]
Hey Gabriel, muito massa que mudou para o Obama, só seria mais legal ainda se fosse possível remover os "lorem ipsum", como sei que gasta um tempo pensar no conteúdo, passei a marcação do "Enzo Pascal" como base, desta forma voces conseguem focar no estilo.
Valeu

**Comment by Gabriels999** [comment]
Feito! Obrigado pela dica.
